# Generated by Django 5.1.7 on 2025-08-08 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_participantcompany_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/products')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='api.participantcompany')),
            ],
        ),
    ]
