# Generated by Django 5.1.7 on 2025-08-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedack_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='transportation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
